"""Strict, bounded inputs. No executable/path/firewall fragments in manifests."""
import ipaddress
import json
import re
import uuid
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
DATA = ROOT / "deploy/b1-harness"
VERSION = "b1-harness-v1"
OWNER = "b1-harness"
ENV = {"PATH": "/usr/sbin:/usr/bin:/sbin:/bin", "LANG": "C", "LC_ALL": "C"}
IMAGE = re.compile(r"[a-z0-9][a-z0-9./_-]{0,180}@sha256:[a-f0-9]{64}\Z")


def unique_pairs(pairs):
    result = {}
    for key, value in pairs:
        if key in result:
            raise ValueError("DUPLICATE_FIELD")
        result[key] = value
    return result


def read_json(path, limit=65536):
    with open(path, "rb") as handle:
        raw = handle.read(limit + 1)
    if len(raw) > limit:
        raise ValueError("INPUT_TOO_LARGE")
    return json.loads(raw, object_pairs_hook=unique_pairs)


def validate(value, runnable=False):
    keys = {"schemaVersion", "policyVersion", "image", "internalCidrs"}
    if type(value) is not dict or set(value) != keys:
        raise ValueError("MANIFEST_FIELDS")
    if value["schemaVersion"] != VERSION or value["policyVersion"] != "outscan-special-use-v1":
        raise ValueError("MANIFEST_VERSION")
    image = value["image"]
    if image is not None and (type(image) is not str or not IMAGE.fullmatch(image)):
        raise ValueError("IMMUTABLE_IMAGE_REQUIRED")
    if runnable and image is None:
        raise ValueError("VERIFIED_IMAGE_REQUIRED")
    ranges = value["internalCidrs"]
    if type(ranges) is not list or not 1 <= len(ranges) <= 32:
        raise ValueError("INTERNAL_RANGES")
    for cidr in ranges:
        if type(cidr) is not str or "%" in cidr:
            raise ValueError("INTERNAL_CIDR")
        if str(ipaddress.ip_network(cidr, strict=True)) != cidr:
            raise ValueError("NON_CANONICAL_CIDR")
    if len(set(ranges)) != len(ranges) or "100.100.1.1/32" not in ranges:
        raise ValueError("STAGING_GATEWAY_REQUIRED")
    return value


def run_id(value):
    if type(value) is not str or str(uuid.UUID(value)) != value:
        raise ValueError("RUN_ID")
    return value


def names(run):
    # UUID is generated by controller, never supplied by a manifest.
    short = run_id(run).replace("-", "")[:10]
    return {"anchor": "b1-anchor-" + run, "probe": "b1-probe-" + run,
            "router": "b1-r-" + short, "fixture": "b1-f-" + short,
            "prefix": "b1" + short, "unit": "outscan-b1-" + run}
